name: CI/CD Pipeline for Wisecow App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t wisecow-app:$GITHUB_SHA .
      
      - name: Push Docker image to registry
        run: |
          docker tag wisecow-app:$GITHUB_SHA shrikh2906/wisecow-app:$GITHUB_SHA
          docker push shrikh2906/wisecow-app:$GITHUB_SHA

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v2
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/wisecow-app wisecow=shrikh2906/wisecow-app:$GITHUB_SHA
          kubectl rollout status deployment/wisecow-app
